---
title: "homework_4"
author: "harinath"
date: "2022-10-02"
output:
  pdf_document: default
  html_document: default
---


```{r}
setwd("C:\\Users\\harin\\OneDrive\\Documents\\Statistical_graphs_and_exploration")

```

```{r}
library(tidyverse)
library(geojsonio)
library(leaflet)
library(dplyr)
library(maps)
library(sp)
library(rgeos)
library(htmlwidgets)
library(lubridate)
library(IDDA)
```

```{r}
data("I.state")
data("pop.state")
```

combining I.state and pop.state

```{r}
I.pop.state <- left_join(I.state, pop.state, by="State") %>%
  group_by(State)
I.pop.state
```

```{r}
weekly_data <- I.pop.state%>%
  group_by(State)%>%
  mutate(infections_dec_week = X2020.12.11 - X2020.12.05)%>%
  dplyr::select(State,infections_dec_week)
weekly_data 
```

calculating weekly risk

```{r}
data_with_weekly_risk <- inner_join(weekly_data, pop.state, by="State")%>%
  mutate(weekly_risk = infections_dec_week/population)
data_with_weekly_risk
```

#installing leaflet

```{r}
install.packages("leaflet")
devtools::install_github("rstudio/leaflet")
```

```{r}
library(geojsonio)
urlRemote  <- "https://raw.githubusercontent.com/"
pathGithub <- "PublicaMundi/MappingAPI/master/data/geojson/"
fileName   <- "us-states.json"
states_data <- geojson_read(x = paste0(urlRemote, pathGithub, fileName), 
                          what = "sp")
class(states_data)
head(states_data@data)
```


```{r}

library(geojsonio); library(leaflet); library(dplyr);
library(IDDA); data("pop.state"); data("I.state")
library(maps); library(lubridate); library(leaflet)
```


```{r}

bins.states <- c(0,1e-3,4e-3,6e-3,8e-3,10e-3)
pal.state.bins <- colorBin(palette="YlOrRd",domain=
                             data_with_weekly_risk$weekly_risk,bins=bins.states)


labels_cases <-sprintf("<strong>%s</strong><br/>Population: %g M<br>
  Weekly_risk: %g<br>infections_in_dec_week:%g",
  data_with_weekly_risk$State,
  round(data_with_weekly_risk$population / (1e4), 2),
  data_with_weekly_risk$weekly_risk * 1e2,
  data_with_weekly_risk$infections_dec_week) %>%
  lapply(htmltools::HTML)
labels_cases[[1]]



dmap %>%addPolygons( data=states_data,
                     fillColor=~pal.state.bins(data_with_weekly_risk$weekly_risk),
                     weight =0.5,opacity = 0.5,color = "white",
                     dashArray="3",fillOpacity = 0.9, layerId =
                       ~State,highlight =highlightOptions(weight =
                                                          2,color="#666",dashArray=
                                                            NULL,fillOpacity
                                                          =0.9,bringToFront =TRUE),
                     label=labels_cases,labelOptions=labelOptions(style=
                                                                list("font-weight"
                                                                ="normal",padding
                                                                ="3px 8px"),
                                                textsize="15px",direction="auto"))



```

```{r}
setwd("C:\\Users\\harin\\OneDrive\\Documents\\Statistical_graphs_and_exploration")
saveWidget(dmap, "Figure1_hw_4.html", selfcontained = F)
```

```{r}
data("I.county")
data("pop.county")
```



```{r}
library(tidyverse)
library(geojsonio)
library(leaflet)
library(dplyr)
library(maps)
library(sp)
library(rgeos)
library(htmlwidgets)
library(lubridate)

```

#combining I.county and pop.county

```{r}
I.pop.county <- left_join(I.county, pop.county, by="State") %>%
  group_by(State)
I.pop.county
```

```{r}
weekly_data <- I.county%>%
  group_by(State)%>%
  mutate(infections_dec_week = X2020.12.11 - X2020.12.05)%>%
  dplyr::select(State,infections_dec_week)
weekly_data 


```

```{r}
data_with_weekly_risk <- inner_join(weekly_data, pop.county, by="State")%>%
  mutate(weekly_risk = infections_dec_week/population)
data_with_weekly_risk

```

```{r}
library(geojsonio); library(leaflet); library(dplyr)
library(IDDA); data("pop.county"); data("I.county")

```

```{r}
urlRemote  <- "https://raw.githubusercontent.com/"
pathGithub <- "plotly/datasets/master/"
fileName   <- "geojson-counties-fips.json"
counties_data <- geojson_read(x = paste0(urlRemote, pathGithub, fileName), 
                          what = "sp")
class(counties_data)

head(counties_data@data)

```

```{r}

labels_cases <- sprintf("<strong>%s</strong><br/>Population: %g M<br>
  Weekly_risk: %g<br>
  infections_in_dec_week: %g",
  data_with_weekly_risk$County, round(data_with_weekly_risk$population / (1e6), 2),
  data_with_weekly_risk$weekly_risk, data_with_weekly_risk$infections_dec_week)%>%
  lapply(htmltools::HTML)
labels_cases[[1]]

pal.county.quantile <- colorQuantile(palette = "YlOrRd", domain = data_with_weekly_risk$weekly_risk, n = 8)


dmap%>%
  
  addMapPane("polygons", zIndex = 410) %>%
  addMapPane("borders", zIndex = 420) %>%
  
# Add state polygons (borders pane)
  addPolygons(data = states_data, fill = FALSE, weight = 1,color ="gray",fillOpacity=0,options=pathOptions(pane=
                                                                                                        "borders"))%>%
  
# Add county polygons (polygons pane)
  addPolygons(data = counties_data,fillColor = ~pal.county.quantile(data_with_weekly_risk$weekly_risk),weight = 1,
              opacity = 0.9, color =
                "gray",dashArray = "3", fillOpacity = 0.9,highlight = highlightOptions(weight = 5, color =
                                                                                         "#666",dashArray =
                                                                                         NULL, fillOpacity =0.9,
                                                                                       bringToFront = TRUE),
              label = labels_cases,layerId = ~id,labelOptions = labelOptions(style = list("font-weight" =
                                                                                                   "normal",
                                                                                                 padding = "3px
                                                                                                 8px"),textsize
                                                                                    = "15px", direction =
                                                                                      "auto"),options =
                pathOptions(pane = "polygons")) %>%
  addLegend(data = counties_data, pal = pal.county.quantile,values = ~data_with_weekly_risk$Infected, opacity = 0.7, title =
              NULL,position = "bottomright")

  
  





setwd("C:\\Users\\harin\\OneDrive\\Documents\\Statistical_graphs_and_exploration")
saveWidget(dmap, "Figure2_hw_4.html", selfcontained = F)





```
